name: whitelist
version: '${project.version}'
main: nl.salvemundi.plugins.Whitelist
api-version: '1.20'
commands:
  get-whitelist-samu:
    description: Get the whitelist with all mc usernames.
    usage: /get-whitelist-samu
